version: '2.4'

services:

  postgres:
    image: postgres:9.6.2-alpine
    environment:
      POSTGRES_USER: taskmanagement
      POSTGRES_PASSWORD: taskmanagement
      POSTGRES_DB: taskmanagement
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "taskmanagement"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
